### ISSUE TITLE
Tree extraction

### ISSUE THREAD

**Issue by Kholoud00** [3dgeo-heidelberg/syssifoss#1]
Can you explain to me please how can I use your code to extract trees from my own las point cloud?

**Comment by han16nah** [comment]
Dear @Kholoud00,

in this repository, we only have scripts for "extracting" point clouds when already having single trees extracted from another, higher resolution point cloud. In our case, we had terrestrial, UAV-borne and airborne laser scanning data and segmented/extracted individual trees in TLS data (automatically) and ULS data (manually in CloudCompare). We then used the extracted trees from the one dataset to extract the same trees from another overlapping dataset (acquired from a different platform) using a nearest neighbour search.

For tree extraction from TLS data, we used [Computree](http://computree.onf.fr/?page_id=589) with several of its plugins, including SimpleForest (formerly SimpleTree). Can be downloaded here: https://simpleforest.org/pages/download.html
 As a guideline, I used example scripts provided by Jan Hackenberg as well as his [video series from 2017 on YouTube](https://www.youtube.com/channel/UCq2dqxUF3IGmusX0ptk7xhw/videos)
 In the meantime, he also put some more videos online.
 
From which dataset do you need to extract trees? In case of ULS or ALS data, you can also look into [lidR](https://github.com/r-lidar/lidR) (an R package).
If you are working with TLS data, an alternative to CompuTree could be [treeseg](https://github.com/apburt/treeseg) if you are familiar with Linux. 

You could also have a look into [FSCT](https://github.com/SKrisanski/FSCT)

Best,

Hannah

**Comment by Kholoud00** [comment]
Thank you Hannah for these informations, I'll try them.
